// Generated by scripts/build-official-plugins.py. Do not edit directly.
const MDVOfficialRenderers = (() => {
  const escapeHtml = (value) => String(value ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

  const escapeAttr = (value) => escapeHtml(value).replace(/`/g, "&#96;");

  const textStats = (source) => {
    const lineCount = Math.max(1, String(source ?? "").split(/\r\n|\r|\n/).length);
    const characterCount = [...String(source ?? "")].filter((ch) => !/\s/u.test(ch)).length;
    const wordCount = String(source ?? "").trim() ? String(source).trim().split(/\s+/u).length : 0;
    return {
      lineCount,
      wordCount,
      characterCount,
      estimatedReadMinutes: wordCount === 0 ? 0 : Math.max(1, Math.ceil(wordCount / 350)),
    };
  };

  const fallback = (label, error, language, source) => ({
    html: `<div class="structured-view structured-${escapeAttr(language)}"><div class="structured-parse-warning"><div class="structured-parse-warning-title">${escapeHtml(label)} 无法按结构解析，已改为原文查看</div><div class="structured-parse-warning-detail">${escapeHtml(error)}</div></div><pre class="structured-source-fallback"><code class="language-${escapeAttr(language)}">${escapeHtml(source)}</code></pre></div>`,
    ...textStats(source),
  });

  function renderTree(value, options = {}) {
    const { rootLabel = "root", openDepth = 1 } = options;
    const stats = { nodes: 0, maxDepth: 0 };

    function kindOf(item) {
      if (Array.isArray(item)) return "array";
      if (item === null) return "null";
      return typeof item === "object" ? "object" : typeof item;
    }

    function keyHtml(key, isIndex) {
      if (key == null) return "";
      return isIndex
        ? `<span class="tree-key tree-index">${escapeHtml(key)}</span><span class="tree-separator">:</span>`
        : `<span class="tree-key">${escapeHtml(key)}</span><span class="tree-separator">:</span>`;
    }

    function primitiveHtml(item) {
      if (item === null) return '<span class="tree-value tree-null">null</span>';
      if (typeof item === "boolean") return `<span class="tree-value tree-bool">${item}</span>`;
      if (typeof item === "number") return `<span class="tree-value tree-number">${escapeHtml(item)}</span>`;
      const string = String(item);
      if (/^https?:\/\/[^\s]+$/i.test(string)) {
        return `<span class="tree-value tree-string">&quot;<a href="${escapeAttr(string)}">${escapeHtml(string)}</a>&quot;</span>`;
      }
      const semantic = /^\d{4}-\d{2}-\d{2}(?:[T ][^\s]+)?$/.test(string) ? " tree-date" : "";
      return `<span class="tree-value tree-string${semantic}">&quot;${escapeHtml(string)}&quot;</span>`;
    }

    function visit(item, key, isIndex, depth) {
      stats.nodes += 1;
      stats.maxDepth = Math.max(stats.maxDepth, depth);
      const kind = kindOf(item);
      if (kind === "object" || kind === "array") {
        const entries = kind === "array" ? item.map((child, index) => [String(index), child, true]) : Object.entries(item).map(([childKey, child]) => [childKey, child, false]);
        const open = depth <= openDepth ? " open" : "";
        const symbol = kind === "array" ? "[ ]" : "{ }";
        const cls = kind === "array" ? "array" : "object";
        const children = entries.map(([childKey, child, childIsIndex]) => visit(child, childKey, childIsIndex, depth + 1)).join("");
        return `<details class="tree-node tree-container tree-${cls}"${open}><summary><span class="tree-chevron" aria-hidden="true"></span>${keyHtml(key, isIndex)}${key == null ? `<span class="tree-root-label">${escapeHtml(rootLabel)}</span>` : ""}<span class="tree-kind tree-kind-${cls}">${symbol}</span><span class="tree-count">${entries.length}</span></summary><div class="tree-children" data-depth="${depth}">${children}</div></details>`;
      }
      return `<div class="tree-node tree-leaf">${keyHtml(key, isIndex)}${primitiveHtml(item)}</div>`;
    }

    return { html: visit(value, null, false, 0), stats };
  }

  function parseYaml(source) {
    const lines = String(source).replace(/\r\n?/g, "\n").split("\n");
    const meaningful = lines.map((raw, lineIndex) => {
      const expanded = raw.replace(/\t/g, "  ");
      const trimmed = stripYamlComment(expanded).trimEnd();
      if (!trimmed.trim() || trimmed.trimStart().startsWith("---") || trimmed.trimStart().startsWith("...")) return null;
      const indent = trimmed.match(/^ */)?.[0].length ?? 0;
      return { indent, text: trimmed.slice(indent), line: lineIndex + 1 };
    }).filter(Boolean);
    if (meaningful.length === 0) return {};

    function parseScalar(raw) {
      const value = raw.trim();
      if (!value) return {};
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        if (value[0] === '"') {
          try { return JSON.parse(value); } catch (_) {}
        }
        return value.slice(1, -1).replace(/''/g, "'");
      }
      if (/^(null|~)$/i.test(value)) return null;
      if (/^(true|false)$/i.test(value)) return value.toLowerCase() === "true";
      if (/^[-+]?\d+(?:\.\d+)?(?:e[-+]?\d+)?$/i.test(value)) return Number(value);
      if (/^\[.*\]$/.test(value)) return parseFlowArray(value);
      if (/^\{.*\}$/.test(value)) return parseFlowObject(value);
      return value;
    }

    function parseFlowArray(value) {
      const body = value.slice(1, -1).trim();
      if (!body) return [];
      return splitFlow(body).map(parseScalar);
    }

    function parseFlowObject(value) {
      const body = value.slice(1, -1).trim();
      if (!body) return {};
      const result = {};
      for (const part of splitFlow(body)) {
        const colon = findYamlColon(part);
        if (colon < 0) throw new Error(`无法解析 YAML flow object：${part}`);
        result[unquote(part.slice(0, colon).trim())] = parseScalar(part.slice(colon + 1));
      }
      return result;
    }

    let cursor = 0;
    function parseBlock(indent) {
      if (cursor >= meaningful.length) return {};
      const arrayMode = meaningful[cursor].indent === indent && meaningful[cursor].text.startsWith("-");
      const out = arrayMode ? [] : {};
      while (cursor < meaningful.length) {
        const current = meaningful[cursor];
        if (current.indent < indent) break;
        if (current.indent > indent) throw new Error(`YAML 第 ${current.line} 行缩进无法归属到上一层`);

        if (arrayMode) {
          if (!current.text.startsWith("-")) break;
          const rest = current.text.slice(1).trimStart();
          cursor += 1;
          if (!rest) {
            out.push(cursor < meaningful.length && meaningful[cursor].indent > indent ? parseBlock(meaningful[cursor].indent) : null);
            continue;
          }
          const colon = findYamlColon(rest);
          if (colon > 0) {
            const item = {};
            const key = unquote(rest.slice(0, colon).trim());
            const tail = rest.slice(colon + 1).trim();
            item[key] = tail ? parseScalar(tail) : (cursor < meaningful.length && meaningful[cursor].indent > indent ? parseBlock(meaningful[cursor].indent) : {});
            if (cursor < meaningful.length && meaningful[cursor].indent > indent) {
              const extra = parseBlock(meaningful[cursor].indent);
              if (extra && !Array.isArray(extra) && typeof extra === "object") Object.assign(item, extra);
            }
            out.push(item);
          } else {
            out.push(parseScalar(rest));
            if (cursor < meaningful.length && meaningful[cursor].indent > indent) parseBlock(meaningful[cursor].indent);
          }
          continue;
        }

        if (current.text.startsWith("-")) break;
        const colon = findYamlColon(current.text);
        if (colon <= 0) throw new Error(`YAML 第 ${current.line} 行缺少 key: value`);
        const key = unquote(current.text.slice(0, colon).trim());
        const tail = current.text.slice(colon + 1).trim();
        cursor += 1;
        if (tail === "|" || tail === ">") {
          const folded = tail === ">";
          const parts = [];
          const childIndent = cursor < meaningful.length ? meaningful[cursor].indent : indent + 2;
          while (cursor < meaningful.length && meaningful[cursor].indent > indent) {
            parts.push(meaningful[cursor].text);
            cursor += 1;
          }
          out[key] = parts.join(folded ? " " : "\n");
        } else if (tail) {
          out[key] = parseScalar(tail);
        } else if (cursor < meaningful.length && meaningful[cursor].indent > indent) {
          out[key] = parseBlock(meaningful[cursor].indent);
        } else {
          out[key] = {};
        }
      }
      return out;
    }

    return parseBlock(meaningful[0].indent);
  }

  function stripYamlComment(line) {
    let quote = null;
    for (let i = 0; i < line.length; i += 1) {
      const ch = line[i];
      if (quote) {
        if (ch === quote && line[i - 1] !== "\\") quote = null;
      } else if (ch === '"' || ch === "'") quote = ch;
      else if (ch === "#" && (i === 0 || /\s/.test(line[i - 1]))) return line.slice(0, i);
    }
    return line;
  }

  function findYamlColon(text) {
    let quote = null;
    let depth = 0;
    for (let i = 0; i < text.length; i += 1) {
      const ch = text[i];
      if (quote) {
        if (ch === quote && text[i - 1] !== "\\") quote = null;
        continue;
      }
      if (ch === '"' || ch === "'") { quote = ch; continue; }
      if (ch === "[" || ch === "{") depth += 1;
      else if (ch === "]" || ch === "}") depth -= 1;
      else if (ch === ":" && depth === 0) return i;
    }
    return -1;
  }

  function splitFlow(text) {
    const parts = [];
    let quote = null;
    let depth = 0;
    let start = 0;
    for (let i = 0; i < text.length; i += 1) {
      const ch = text[i];
      if (quote) {
        if (ch === quote && text[i - 1] !== "\\") quote = null;
        continue;
      }
      if (ch === '"' || ch === "'") quote = ch;
      else if (ch === "[" || ch === "{") depth += 1;
      else if (ch === "]" || ch === "}") depth -= 1;
      else if (ch === "," && depth === 0) { parts.push(text.slice(start, i).trim()); start = i + 1; }
    }
    parts.push(text.slice(start).trim());
    return parts.filter(Boolean);
  }

  function unquote(value) {
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) return value.slice(1, -1);
    return value;
  }

  function parseToml(source) {
    const root = {};
    let current = root;
    const lines = String(source).replace(/\r\n?/g, "\n").split("\n");

    function ensurePath(target, path) {
      let node = target;
      for (const key of path) {
        if (!node[key] || typeof node[key] !== "object" || Array.isArray(node[key])) node[key] = {};
        node = node[key];
      }
      return node;
    }

    function parseValue(raw) {
      const value = raw.trim();
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        if (value[0] === '"') { try { return JSON.parse(value); } catch (_) {} }
        return value.slice(1, -1);
      }
      if (/^(true|false)$/i.test(value)) return value.toLowerCase() === "true";
      if (/^[-+]?\d[\d_]*(?:\.\d[\d_]*)?(?:e[-+]?\d+)?$/i.test(value)) return Number(value.replace(/_/g, ""));
      if (value.startsWith("[") && value.endsWith("]")) return splitFlow(value.slice(1, -1)).map(parseValue);
      if (value.startsWith("{") && value.endsWith("}")) {
        const obj = {};
        for (const part of splitFlow(value.slice(1, -1))) {
          const eq = findUnquoted(part, "=");
          if (eq < 1) throw new Error(`TOML inline table 无法解析：${part}`);
          obj[unquote(part.slice(0, eq).trim())] = parseValue(part.slice(eq + 1));
        }
        return obj;
      }
      return value;
    }

    for (let index = 0; index < lines.length; index += 1) {
      const line = stripTomlComment(lines[index]).trim();
      if (!line) continue;
      const arrayTable = line.match(/^\[\[(.+)\]\]$/);
      if (arrayTable) {
        const path = splitDottedKey(arrayTable[1]);
        const parent = ensurePath(root, path.slice(0, -1));
        const key = path.at(-1);
        if (!Array.isArray(parent[key])) parent[key] = [];
        const row = {};
        parent[key].push(row);
        current = row;
        continue;
      }
      const table = line.match(/^\[(.+)\]$/);
      if (table) {
        current = ensurePath(root, splitDottedKey(table[1]));
        continue;
      }
      const eq = findUnquoted(line, "=");
      if (eq < 1) throw new Error(`TOML 第 ${index + 1} 行缺少 key = value`);
      const path = splitDottedKey(line.slice(0, eq));
      const parent = ensurePath(current, path.slice(0, -1));
      parent[path.at(-1)] = parseValue(line.slice(eq + 1));
    }
    return root;
  }

  function stripTomlComment(line) {
    let quote = null;
    for (let i = 0; i < line.length; i += 1) {
      const ch = line[i];
      if (quote) {
        if (ch === quote && line[i - 1] !== "\\") quote = null;
      } else if (ch === '"' || ch === "'") quote = ch;
      else if (ch === "#") return line.slice(0, i);
    }
    return line;
  }

  function findUnquoted(text, target) {
    let quote = null;
    let depth = 0;
    for (let i = 0; i < text.length; i += 1) {
      const ch = text[i];
      if (quote) {
        if (ch === quote && text[i - 1] !== "\\") quote = null;
        continue;
      }
      if (ch === '"' || ch === "'") quote = ch;
      else if (ch === "[" || ch === "{") depth += 1;
      else if (ch === "]" || ch === "}") depth -= 1;
      else if (ch === target && depth === 0) return i;
    }
    return -1;
  }

  function splitDottedKey(text) {
    const result = [];
    let quote = null;
    let start = 0;
    const value = text.trim();
    for (let i = 0; i < value.length; i += 1) {
      const ch = value[i];
      if (quote) {
        if (ch === quote && value[i - 1] !== "\\") quote = null;
      } else if (ch === '"' || ch === "'") quote = ch;
      else if (ch === ".") { result.push(unquote(value.slice(start, i).trim())); start = i + 1; }
    }
    result.push(unquote(value.slice(start).trim()));
    return result.filter(Boolean);
  }

  function parseCsv(source) {
    const rows = [];
    let row = [];
    let field = "";
    let quoted = false;
    const text = String(source ?? "");
    for (let i = 0; i <= text.length; i += 1) {
      const ch = text[i] ?? "\n";
      if (quoted) {
        if (ch === '"' && text[i + 1] === '"') { field += '"'; i += 1; }
        else if (ch === '"') quoted = false;
        else field += ch;
        continue;
      }
      if (ch === '"' && field.length === 0) { quoted = true; continue; }
      if (ch === ",") { row.push(field); field = ""; continue; }
      if (ch === "\r" && text[i + 1] === "\n") { i += 1; row.push(field); rows.push(row); row = []; field = ""; continue; }
      if (ch === "\n") { row.push(field); if (row.length > 1 || row[0] !== "" || i < text.length) rows.push(row); row = []; field = ""; continue; }
      field += ch;
    }
    if (quoted) throw new Error("CSV 存在未闭合的引号字段");
    return rows;
  }

  function json(document) {
    try {
      const value = JSON.parse(document.source);
      const tree = renderTree(value);
      const kind = Array.isArray(value) ? "数组" : value === null ? "Null" : typeof value === "object" ? "对象" : typeof value;
      return {
        html: `<div class="structured-view structured-json"><div class="json-viewer-toolbar"><div class="json-viewer-heading"><span class="json-format-badge">JSON</span><span class="json-root-kind">${kind}</span><span class="json-stat">${tree.stats.nodes} 个节点</span><span class="json-stat">${tree.stats.maxDepth + 1} 层</span></div><div class="json-viewer-actions"><button type="button" class="json-action" data-plugin-action="expand-details">展开全部</button><button type="button" class="json-action" data-plugin-action="collapse-details">收起全部</button></div></div><div class="json-tree">${tree.html}</div></div>`,
        ...textStats(document.source),
      };
    } catch (error) {
      return fallback("JSON", error instanceof Error ? error.message : String(error), "json", document.source);
    }
  }

  function yaml(document) {
    try {
      const value = parseYaml(document.source);
      const tree = renderTree(value);
      return { html: `<div class="structured-view structured-yaml"><div class="structured-toolbar-hint">YAML Tree</div><div class="json-tree">${tree.html}</div></div>`, ...textStats(document.source) };
    } catch (error) {
      return fallback("YAML", error instanceof Error ? error.message : String(error), "yaml", document.source);
    }
  }

  function toml(document) {
    try {
      const value = parseToml(document.source);
      const tree = renderTree(value);
      return { html: `<div class="structured-view structured-toml"><div class="structured-toolbar-hint">TOML Tree</div><div class="json-tree">${tree.html}</div></div>`, ...textStats(document.source) };
    } catch (error) {
      return fallback("TOML", error instanceof Error ? error.message : String(error), "toml", document.source);
    }
  }

  function csv(document) {
    try {
      const rows = parseCsv(document.source);
      const headers = rows[0] ?? [];
      const body = rows.slice(1, 2001);
      const headerHtml = headers.map((cell) => `<th>${escapeHtml(cell)}</th>`).join("");
      const rowsHtml = body.map((record) => `<tr>${headers.map((_, index) => `<td>${escapeHtml(record[index] ?? "")}</td>`).join("")}</tr>`).join("");
      const truncated = rows.length > 2001 ? '<div class="structured-note">为保证流畅度，预览仅显示前 2,000 行。全文搜索仍可覆盖受限大小内的原文件。</div>' : "";
      return { html: `<div class="structured-view structured-csv"><div class="structured-toolbar-hint">CSV Table</div><div class="csv-table-scroll"><table class="csv-table"><thead><tr>${headerHtml}</tr></thead><tbody>${rowsHtml}</tbody></table></div>${truncated}</div>`, ...textStats(document.source) };
    } catch (error) {
      return fallback("CSV", error instanceof Error ? error.message : String(error), "plaintext", document.source);
    }
  }

  function log(document) {
    const MAX_LINES = 12000;
    const lines = String(document.source).replace(/\r\n?/g, "\n").split("\n");
    const rendered = lines.slice(0, MAX_LINES).map((line, index) => {
      const match = line.match(/(?:^|[\s\[({])(?:FATAL|ERROR|ERR|WARN|WARNING|INFO|DEBUG|TRACE)(?:\]|\)|\}|:|\s|$)/i);
      const rawLevel = match?.[0]?.match(/FATAL|ERROR|ERR|WARN|WARNING|INFO|DEBUG|TRACE/i)?.[0]?.toUpperCase() ?? "INFO";
      const level = rawLevel === "WARNING" ? "WARN" : (rawLevel === "ERR" || rawLevel === "FATAL") ? "ERROR" : rawLevel;
      return `<div class="log-row log-${level.toLowerCase()}"><span class="log-line-no">${index + 1}</span><span class="log-level">${level}</span><span class="log-text">${escapeHtml(line)}</span></div>`;
    }).join("");
    const note = lines.length > MAX_LINES ? `<div class="structured-note">日志共 ${lines.length} 行，为保证流畅度当前展示前 ${MAX_LINES} 行；工作区全文搜索仍可扫描受限大小内的完整文件。</div>` : "";
    return { html: `<div class="structured-view structured-log"><div class="structured-toolbar-hint">Log Viewer</div><div class="log-view">${rendered}</div>${note}</div>`, ...textStats(document.source) };
  }

  function diff(document) {
    const MAX_LINES = 20000;
    const lines = String(document.source).replace(/\r\n?/g, "\n").split("\n");
    let additions = 0, deletions = 0, files = 0;
    for (const line of lines) {
      if (line.startsWith("diff --git ")) files += 1;
      else if (line.startsWith("+") && !line.startsWith("+++")) additions += 1;
      else if (line.startsWith("-") && !line.startsWith("---")) deletions += 1;
    }
    if (files === 0 && (document.source.includes("--- ") || document.source.includes("+++ "))) files = 1;
    const rows = lines.slice(0, MAX_LINES).map((line, index) => {
      let cls = "";
      if (line.startsWith("diff --git ") || line.startsWith("index ") || line.startsWith("--- ") || line.startsWith("+++ ")) cls = "diff-meta";
      else if (line.startsWith("@@")) cls = "diff-hunk";
      else if (line.startsWith("+") && !line.startsWith("+++")) cls = "diff-add";
      else if (line.startsWith("-") && !line.startsWith("---")) cls = "diff-del";
      else if (line.startsWith("\ No newline")) cls = "diff-note";
      return `<div class="diff-row ${cls}"><span class="diff-line-no">${index + 1}</span><code>${escapeHtml(line)}</code></div>`;
    }).join("");
    const note = lines.length > MAX_LINES ? `<div class="structured-note">Diff 共 ${lines.length} 行，为保证流畅度当前展示前 ${MAX_LINES} 行。</div>` : "";
    return { html: `<div class="structured-view structured-diff"><div class="diff-summary"><span>${files} file${files === 1 ? "" : "s"}</span><span class="diff-add-count">+${additions}</span><span class="diff-del-count">−${deletions}</span></div><div class="diff-view">${rows}</div>${note}</div>`, ...textStats(document.source) };
  }

  return Object.freeze({ json, yaml, toml, csv, log, diff });
})();


markdownViewer.definePlugin({
  documentFormats: {
    "json": { render: MDVOfficialRenderers.json },
    "yaml": { render: MDVOfficialRenderers.yaml },
    "toml": { render: MDVOfficialRenderers.toml },
    "csv": { render: MDVOfficialRenderers.csv },
    "log": { render: MDVOfficialRenderers.log },
    "diff": { render: MDVOfficialRenderers.diff }
  }
});
