#!/usr/bin/env python3
from __future__ import annotations

import json
import shutil
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OFFICIAL = ROOT / "official-plugins"
SHARED = (OFFICIAL / "_shared" / "renderers.js").read_text(encoding="utf-8")
DIST = OFFICIAL / "dist"
APP_MIN_VERSION = "0.21.0"

FORMATS = {
    "json-viewer": {
        "id": "com.markdownviewer.official.json-viewer",
        "name": "JSON Viewer",
        "description": "JSON 折叠树、节点统计、语义值提示与搜索展开体验。",
        "formats": [{"id": "json", "label": "JSON", "extensions": ["json"]}],
    },
    "yaml-viewer": {
        "id": "com.markdownviewer.official.yaml-viewer",
        "name": "YAML Viewer",
        "description": "YAML 配置文件的只读层级树查看器。",
        "formats": [{"id": "yaml", "label": "YAML", "extensions": ["yaml", "yml"]}],
    },
    "toml-viewer": {
        "id": "com.markdownviewer.official.toml-viewer",
        "name": "TOML Viewer",
        "description": "TOML 配置文件的只读层级树查看器。",
        "formats": [{"id": "toml", "label": "TOML", "extensions": ["toml"]}],
    },
    "csv-viewer": {
        "id": "com.markdownviewer.official.csv-viewer",
        "name": "CSV Viewer",
        "description": "CSV 表格预览，支持引号、逗号和多行字段解析。",
        "formats": [{"id": "csv", "label": "CSV", "extensions": ["csv"]}],
    },
    "log-viewer": {
        "id": "com.markdownviewer.official.log-viewer",
        "name": "LOG Viewer",
        "description": "日志行号与 ERROR/WARN/INFO/DEBUG/TRACE 语义分层。",
        "formats": [{"id": "log", "label": "LOG", "extensions": ["log"]}],
    },
    "diff-viewer": {
        "id": "com.markdownviewer.official.diff-viewer",
        "name": "Diff Viewer",
        "description": "Unified Diff / Patch 文件的增删行、hunk 与摘要查看器。",
        "formats": [{"id": "diff", "label": "DIFF / PATCH", "extensions": ["diff", "patch"]}],
    },
}

PACK = {
    "id": "com.markdownviewer.official.developer-pack",
    "name": "Developer Pack",
    "description": "官方开发文档格式包：JSON、YAML、TOML、CSV、LOG、DIFF/PATCH。",
    "formats": [fmt for spec in FORMATS.values() for fmt in spec["formats"]],
}


def manifest(spec: dict) -> dict:
    return {
        "id": spec["id"],
        "name": spec["name"],
        "version": "1.2.0",
        "description": spec["description"],
        "author": "oneView",
        "apiVersion": 1,
        "minAppVersion": APP_MIN_VERSION,
        "runtime": {"kind": "worker", "role": "document", "main": "main.js"},
        "permissions": [],
        "contributes": {"documentFormats": spec["formats"], "themes": []},
    }


def main_js(spec: dict) -> str:
    mappings = []
    for fmt in spec["formats"]:
        renderer = "diff" if fmt["id"] == "diff" else fmt["id"]
        mappings.append(f'    {json.dumps(fmt["id"])}: {{ render: MDVOfficialRenderers.{renderer} }}')
    return (
        "// Generated by scripts/build-official-plugins.py. Do not edit directly.\n"
        + SHARED
        + "\n\nmarkdownViewer.definePlugin({\n  documentFormats: {\n"
        + ",\n".join(mappings)
        + "\n  }\n});\n"
    )


def readme(spec: dict, folder_name: str) -> str:
    lines = [
        f"# {spec['name']}",
        "",
        spec["description"],
        "",
        "这是 oneView v0.21+ 的官方 Document Plugin。零权限运行，解析与渲染逻辑进入独立 Sandbox Worker，不进入 Markdown Core 或 Extension Runtime。",
        "",
        "支持格式：",
    ]
    for fmt in spec["formats"]:
        exts = ", ".join(f".{ext}" for ext in fmt["extensions"])
        lines.append(f"- {fmt['label']}: {exts}")
    lines += [
        "",
        "安装：设置 → 插件 → 从本地安装 → 选择对应 `.mdvplugin`。安装后默认关闭，手动启用即可。",
        "",
        f"源码目录：`official-plugins/{folder_name}`",
        "",
    ]
    return "\n".join(lines)


def build_one(folder_name: str, spec: dict):
    folder = OFFICIAL / folder_name
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "manifest.json").write_text(json.dumps(manifest(spec), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (folder / "main.js").write_text(main_js(spec), encoding="utf-8")
    (folder / "README.md").write_text(readme(spec, folder_name), encoding="utf-8")

    target = DIST / f"{folder_name}.mdvplugin"
    with zipfile.ZipFile(target, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for name in ("manifest.json", "main.js", "README.md"):
            zf.write(folder / name, name)
    return target


def build_declarative(folder_name: str):
    """Package a contribution-only plugin without adding a runtime entrypoint."""
    folder = OFFICIAL / folder_name
    manifest_path = folder / "manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(manifest_path)
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    if data.get("main") or data.get("runtime"):
        raise ValueError(f"{folder_name} must remain declaration-only")
    if data.get("permissions") != []:
        raise ValueError(f"{folder_name} must request zero permissions")

    target = DIST / f"{folder_name}.mdvplugin"
    with zipfile.ZipFile(target, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for path in sorted(folder.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(folder).as_posix())
    return target


def main():
    DIST.mkdir(parents=True, exist_ok=True)
    for old in DIST.glob("*.mdvplugin"):
        old.unlink()
    built = [build_one(name, spec) for name, spec in FORMATS.items()]
    built.append(build_one("developer-pack", PACK))
    built.append(build_declarative("slate-theme"))
    for path in built:
        print(f"{path.relative_to(ROOT)}\t{path.stat().st_size} bytes")


if __name__ == "__main__":
    main()
